sudo: required
services:
    - docker

before_install:
    - docker build -t thorvetejal85/react-test -f ./client/Dockerfile.dev

    script:
        - docker run thorvetejal85/react-test npm test -- --cover

     after_Success:
        - docker build -t thorvetejal85/multi-client ./client
        - docker build -t thorvetejal85/multi-nginx ./nginx
        - docker build -t thorvetejal85/multi-server ./server
        - docker build -t thorvetejal85/multi-worker ./worker

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

        - docker push thorvetejal85/multi-client
        - docker push thorvetejal85/multi-nginx
        - docker push thorvetejal85/multi-server
        - docker push thorvetejal85/multi-worker

